version: '3.8'

services:
  postgres:
    image: postgres:latest
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker  
      - POSTGRES_DB=captiondbbr
    volumes:
      - caption_pg_data:/postgresql
  redis:
    image: redis:latest
    container_name: captiondbbr_cache
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - caption_redis_data:/captiondata


volumes:
  caption_pg_data:
  caption_redis_data: